CREATE TABLE ALUMNO
(
	MATRICULA VARCHAR2(20),
	NOMBRE VARCHAR2(50),
	FECHANACIMIENTO DATE,
	TELEFONO NUMBER(9),
	
	CONSTRAINT PK_ALUMNO PRIMARY KEY(MATRICULA)
);

CREATE TABLE PROFESOR
(
	IDPROFESOR VARCHAR2(10),
	NIF_P VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2(50),
	ESPECIALIDAD VARCHAR2(30),
	TELEFONO NUMBER(10),
	
	CONSTRAINT PK_PROFESOR PRIMARY KEY (IDPROFESOR)
);

CREATE TABLE ASIGNATURA
(
	CODASIGNATURA VARCHAR2(20),
	NOMBRE VARCHAR2(30),
	IDPROFESOR VARCHAR2(10),
	
	CONSTRAINT PK_ASIGNATURA PRIMARY KEY (CODASIGNATURA),
	CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (IDPROFESOR) REFERENCES PROFESOR(IDPROFESOR)
);



CREATE TABLE RECIBE
(
	NUMMATRICULA VARCHAR2 (20),
	CODASIGNATURA VARCHAR2(10),
	CURSOESCOLAR NUMBER(2),
	
	CONSTRAINT PK_RECIBE PRIMARY KEY(NUMMATRICULA,CODASIGNATURA,CURSOESCOLAR),
	CONSTRAINT FK1_RECIBE FOREIGN KEY (NUMMATRICULA) REFERENCES ALUMNO(MATRICULA),
	CONSTRAINT FK2_RECIBE FOREIGN KEY (CODASIGNATURA) REFERENCES ASIGNATURA (CODASIGNATURA)
);


