CREATE TABLE CLIENTE
(
	CODCLIENTE NUMBER(10),
	NOMBRE VARCHAR2(20),
	CALLE VARCHAR2(30),
	NUMERO NUMBER(5),
	COMUNA VARCHAR2(20),
	CIUDAD VARCHAR2(20),
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY(CODCLIENTE),
);

CREATE TABLE TELEFONO
(
	NUMERO NUMBER(10),
	
	CONSTRAINT PK_TELEFONO PRIMARY KEY (NUMERO)
);

CREATE TABLE CATEGORIA
(
	IDCATEGORIA
	NOMBRE
	DESCRIPCION
	
	CONSTRAINT PK_CATEGORIA
);

CREATE TABLE PROVEEDOR();
CREATE TABLE PRODUCTO();
CREATE TABLE VENTA();
CREATE TABLE ASOCIADO();
CREATE TABLE INCLUYE();