CREATE TABLE REGION 
(
	CODREGION VARCHAR2(15),
	NOMBRE VARCHAR2(50),
	
	CONSTRAINT PK_REGION PRIMARY KEY (CODREGION)
);

CREATE TABLE PROVINCIA 
(
	CODPROVINCIA VARCHAR2(15),
	NOMBRE VARCHAR2(30),
	CODREGION VARCHAR2(15),
	
	CONSTRAINT PK_PROVINCIA PRIMARY KEY (CODPROVINCIA),
	CONSTRAINT FK1_PROVINCIA FOREIGN KEY (CODREGION) REFERENCES REGION(CODREGION)
);

CREATE TABLE LOCALIDAD 
(
	CODLOCALIDAD VARCHAR2(15),
	NOMBRE VARCHAR2(50),
	CODPROVINCIA VARCHAR2(15),
	
	CONSTRAINT PK_LOCALIDAD PRIMARY KEY(CODLOCALIDAD),
	CONSTRAINT FK1_LOCALIDAD FOREIGN KEY(CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);

CREATE TABLE EMPLEADO 
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(50),
	FECHANAC DATE,
	TELEFONO NUMBER(13),
	SALARIO NUMBER(10,2),
	CODLOCALIDAD VARCHAR2(15),
	
	CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);



