CREATE TABLE CLIENTE 
(
	CODCLIENTE VARCHAR2 (20),
	DNI VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2 (30) NOT NULL,
	DIRECCION VARCHAR2 (50),
	TELEFONO NUMBER (9),
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLIENTE)
);

CREATE TABLE RESERVA
(
	NUMERO NUMBER(10),
	FECHAINICIO DATE,
	PRECIOTOTAL NUMBER(10,2),
	CODCLIENTE VARCHAR2(20),
	
	CONSTRAINT PK_RESERVA PRIMARY KEY (NUMERO),
	CONSTRAINT FK1_RESERVA FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE COCHE 
(
	MATRICULA VARCHAR2(10),
	MARCA VARCHAR2(20) NOT NULL,
	MODELO VARCHAR2(20) NOT NULL,
	COLOR VARCHAR2(20),
	PRECIOHORA NUMBER(10,2),
	
	CONSTRAINT PK_COCHE PRIMARY KEY (MATRICULA)
);

CREATE TABLE AVALA 
(
	AVALADO VARCHAR2(20),
	AVALADOR VARCHAR2(20),
	
	CONSTRAINT PK_AVALA PRIMARY KEY(AVALADO),
	CONSTRAINT FK1_AVALA FOREIGN KEY(AVALADO) REFERENCES CLIENTE(CODCLIENTE),
	CONSTRAINT FK2_AVALA FOREIGN KEY (AVALADOR) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE INCLUYE 
(
	NUMERO NUMBER(10),
	MATRICULA VARCHAR2(10),
	LITROSGAS NUMBER(3),
	
	CONSTRAINT PK_INCLUYE PRIMARY KEY (NUMERO,MATRICULA),
	CONSTRAINT FK1_INCLUYE FOREIGN KEY (NUMERO) REFERENCES RESERVA(NUMERO),
	CONSTRAINT FK2_INCLUYE FOREIGN KEY (MATRICULA) REFERENCES COCHE(MATRICULA)
);