CREATE TABLE SUCURSAL
(
	CODIGO VARCHAR2(10),
	DIRECCION VARCHAR2(50),
	TELEFONO VARCHAR2(9),
	
	CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(25) NOT NULL,
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	SUCURSAL VARCHAR2(10),
	
	CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI),
	CONSTRAINT FK1_EMPLEADO FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE PERIODISTA
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30) NOT NULL,
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	ESPECIALISTA VARCHAR2(30),
	
	CONSTRAINT PK_PERIODISTA PRIMARY KEY(DNI)
);

CREATE TABLE REVISTA
(
	NUMREG NUMBER(10),
	TITULO VARCHAR2(20) NOT NULL,
	PERIODICIDAD VARCHAR2(20) DEFAULT 'MENSUAL',
	TIPO VARCHAR2(10),
	SUCURSAL VARCHAR2(10),
	
	CONSTRAINT PK_REVISTA PRIMARY KEY(NUMREG),
	CONSTRAINT FK1_REVISTA FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO),
	CONSTRAINT CHECK_REVISTA CHECK(PERIODICIDAD IN ('SEMANAL','QUINCENAL','MENSUAL','TRIMESTRAL','ANUAL'))
);

CREATE TABLE NUMREVISTA
(
	NUMREG NUMBER(10),
	NUMERO NUMBER(5),
	NUMPAGINAS NUMBER(5) DEFAULT 1,
	FECHA DATE,
	CANTVENDIDAS NUMBER(4),
	
	CONSTRAINT PK_NUMREVISTA PRIMARY KEY(NUMREG,NUMERO),
	CONSTRAINT FK1_NUMREVISTA FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG)
);
CREATE TABLE ESCRIBE
(
	NUMREG NUMBER(10),
	DNI_PER VARCHAR2(10),
	
	CONSTRAINT PK_ESCRIBE PRIMARY KEY(NUMREG,DNI_PER),
	CONSTRAINT FK1_ESCRIBE FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG),
	CONSTRAINT FK2_ESCRIBE FOREIGN KEY(DNI_PER) REFERENCES PERIODISTA(DNI)
);
