CREATE TABLE SOCIO
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30)NOT NULL,
	DIRECCION VARCHAR2(50),
	TELEFONO VARCHAR2(10),
	AVALADOR VARCHAR2(20),
	
	CONSTRAINT PK_SOCIO PRIMARY KEY(DNI)
);

CREATE TABLE ACTORES
(
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	SEXO VARCHAR2(1) CHECK (SEXO IN('H','M')),
	
	CONSTRAINT PK_ACTORES PRIMARY KEY (NOMBRE)
);

CREATE TABLE DIRECTOR
(
	NOMBRE VARCHAR2(30),
	NACIONALIDAD VARCHAR2(20),
	
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (NOMBRE)
);

CREATE TABLE PELICULA
(
	ID VARCHAR2(3),
	TITULO VARCHAR2(20) NOT NULL,
	PRODUCTORA VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	FECHA DATE,
	DIRECTOR VARCHAR2(20),
	
	CONSTRAINT PK_PELICULA PRIMARY KEY(ID),
	CONSTRAINT FK1_PELICULA FOREIGN KEY(DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE EJEMPLAR
(
	ID_PELI VARCHAR2(5),
	NUMERO NUMBER(5),
	ESTADO VARCHAR2(3),
	
	CONSTRAINT PK_EJEMPLAR PRIMARY KEY(ID_PELI,NUMERO),
	CONSTRAINT FK1_EJEMPLAR FOREIGN KEY(ID_PELI) REFERENCES PELICULA(ID)
);


CREATE TABLE ALQUILA
(
	DNI VARCHAR2(10),
	ID_PELI VARCHAR2(3),
	NUMERO NUMBER(5),
	FECHAALQUILER DATE,
	FECHADEVOLUCION DATE,
	
	CONSTRAINT PK_ALQUILA PRIMARY KEY(DNI,ID_PELI,NUMERO,FECHAALQUILER),
	CONSTRAINT FK1_ALQUILA FOREIGN KEY(DNI) REFERENCES SOCIO(DNI),
	CONSTRAINT FK2_ALQUILA FOREIGN KEY(ID_PELI,NUMERO) REFERENCES EJEMPLAR(ID_PELI,NUMERO)
);


CREATE TABLE ACTUA
(
	ACTOR VARCHAR2(20),
	ID_PELI VARCHAR2(3),
	PROTA VARCHAR2(1) DEFAULT 'N',
	
	CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR,ID_PELI),
	CONSTRAINT FK1_ACTUA FOREIGN KEY(ACTOR) REFERENCES ACTORES(NOMBRE),
	CONSTRAINT FK2_ACTUA FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID),
	CONSTRAINT CHECK_ACTUAL CHECK (PROTA IN('S','N'))
);

ALTER TABLE SOCIO ADD CONSTRAINT FK1_SOCIO FOREIGN KEY(AVALADOR) REFERENCES SOCIO(DNI);