CREATE TABLE DIRECCION
(
	CODDIRECCION VARCHAR2(10),
	VIA VARCHAR2(10),
	NOMBREVIA VARCHAR2(20),
	NUMERO NUMBER(3),
	PISO NUMBER(3),
	PORTAL NUMBER (3),
	CODPOSTAL NUMBER(5)
	
);

CREATE TABLE ARTICULO
(
	NUMARTICULO NUMBER(4),
	DESCRIPCION VARCHAR2 (100)
	
);

CREATE TABLE FABRICA
(
	NUMFABRICA NUMBER(5),
	TELEFONO NUMBER(10)
	
);

CREATE TABLE CLIENTE
(
	NUMCLIENTE NUMBER(3),
	SALDO NUMBER(20,2),
	LIMCREDITO NUMBER(20,2),
	DESCUENTO NUMBER(3)
	
);

CREATE TABLE PEDIDO
(
	NUMPEDIDO NUMBER(10),
	FECHA DATE,
	NUMCLIENTE NUMBER(3),
	CODDIRECCION VARCHAR2(10)
	
);

CREATE TABLE POSEE
(
	NUMCLIENTE NUMBER(3),
	CODDIRECCION VARCHAR2(10)
	
);

CREATE TABLE INCLUYE
(
	NUMPEDIDO NUMBER(10),
	NUMARTICULO NUMBER(4),
	CANTIDAD NUMBER(3)
	

);

CREATE TABLE DISTRIBUYE
(
	NUMARTICULO NUMBER(4),
	NUMFABRICA NUMBER(5),
	CANTSUMINISTRO NUMBER(5),
	EXISTENCIAS NUMBER(10)
	
);

-- Tabla direccion
ALTER TABLE DIRECCION ADD PRIMARY KEY (CODDIRECCION);

-- Tabla articulo
ALTER TABLE ARTICULO ADD PRIMARY KEY (NUMARTICULO);
CREATE SEQUENCE SEC_NUMARTICULO START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;

-- Tabla fabrica
ALTER TABLE FABRICA ADD PRIMARY KEY (NUMFABRICA);
CREATE SEQUENCE SEC_NUMFABRICA START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;


-- Tabla cliente
ALTER TABLE CLIENTE ADD PRIMARY KEY (NUMCLIENTE);
CREATE SEQUENCE SEC_NUMCLIENTE START WITH 1 INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1;

-- Tabla pedido
ALTER TABLE PEDIDO ADD PRIMARY KEY(NUMPEDIDO);
ALTER TABLE PEDIDO ADD FOREIGN KEY(NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE PEDIDO ADD FOREIGN KEY(CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);
	
-- Tabla posee
ALTER TABLE POSEE ADD PRIMARY KEY(NUMCLIENTE,CODDIRECCION);
ALTER TABLE POSEE ADD FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE POSEE ADD FOREIGN KEY(CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);

-- Tabla incluye
ALTER TABLE INCLUYE ADD PRIMARY KEY(NUMPEDIDO,NUMARTICULO);
ALTER TABLE INCLUYE ADD FOREIGN KEY(NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO);
ALTER TABLE INCLUYE ADD FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);
	
-- Tabla distribuye
ALTER TABLE DISTRIBUYE ADD PRIMARY KEY (NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD FOREIGN KEY (NUMFABRICA) REFERENCES FABRICA (NUMFABRICA);

