CREATE TABLE EMPLEADO
(
	CODEMP VARCHAR2(5),
	NIF VARCHAR2(10) UNIQUE,
	NOMBRE VARCHAR2(20),
	APELLIDOS VARCHAR2(20),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	FECHANAC DATE,
	SALARIO NUMBER(10,2)
	
);

CREATE TABLE CURSO
(
    CODCURSO VARCHAR2(5),
    NOMBRE VARCHAR2(30),
    DURACION NUMBER(5),
    COSTE NUMBER(10,2)

);

CREATE TABLE EMPCAPACITADO
(
    CODEMP VARCHAR2(5)

);
CREATE TABLE EMPNOCAPACITADO
(
    CODEMP VARCHAR2(5)

);

CREATE TABLE EDICION
(
    CODCURSO VARCHAR2(5),
    FECHAINICIO DATE,
    LUGAR VARCHAR2(30),
    HORARIO VARCHAR2(20),
    PROFESOR VARCHAR2(30)

);

CREATE TABLE RECIBE
(
    CODEMP VARCHAR2(5),
    CODCURSO VARCHAR2(5),
    FECHAINICIO DATE
);

CREATE TABLE PREREQUISITO
(
 CURSOSOLICITADO VARCHAR2(5),
    CURSOPREVIO VARCHAR2(5),
    OBLIGATORIO VARCHAR2(2)
);

--Tabla empleado
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY(CODEMP);

--Tabla curso
ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY(CODCURSO);

--Tabla empcapacitado
ALTER TABLE EMPCAPACITADO ADD CONSTRAINT PK_EMPCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPCAPACITADO ADD CONSTRAINT FK1_EMPCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO(CODEMP);

--Tabla empnocapacitado
ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT PK_EMPNOCAPACITADO PRIMARY KEY (CODEMP);
ALTER TABLE EMPNOCAPACITADO ADD CONSTRAINT FK1_EMPNOCAPACITADO FOREIGN KEY (CODEMP) REFERENCES EMPLEADO(CODEMP);

--Tabla edicion
ALTER TABLE EDICION ADD CONSTRAINT PK_EDICION PRIMARY KEY (CODCURSO, FECHAINICIO);
ALTER TABLE EDICION ADD CONSTRAINT FK1_EDICION FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO);

--Tabla recibe
ALTER TABLE RECIBE ADD CONSTRAINT PK_RECIBE PRIMARY KEY (CODEMP, CODCURSO, FECHAINICIO);
ALTER TABLE RECIBE ADD CONSTRAINT FK1_RECIBE FOREIGN KEY (CODEMP) REFERENCES EMPLEADO(CODEMP);
ALTER TABLE RECIBE ADD CONSTRAINT FK2_RECIBE FOREIGN KEY (CODCURSO, FECHAINICIO) REFERENCES EDICION(CODCURSO, FECHAINICIO);

--Tabla prerequisito
ALTER TABLE PREREQUISITO ADD CONSTRAINT PK_PREREQUISITO PRIMARY KEY (CURSOSOLICITADO, CURSOPREVIO);
ALTER TABLE PREREQUISITO ADD CONSTRAINT FK1_PREREQUISITO FOREIGN KEY (CURSOSOLICITADO) REFERENCES CURSO(CODCURSO);
ALTER TABLE PREREQUISITO ADD CONSTRAINT FK2_PREREQUISITO FOREIGN KEY (CURSOPREVIO) REFERENCES CURSO(CODCURSO);
ALTER TABLE PREREQUISITO ADD CONSTRAINT CHK1_OBLIGATORIO CHECK (OBLIGATORIO IN ('S','N'));