CREATE TABLE CLIENTE
(
	NIF VARCHAR2(10),
	NOMBRE VARCHAR2(30),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (NIF)
);


CREATE TABLE MODELODORMITORIO
(
	COD VARCHAR2(10),
	
	CONSTRAINT PK_MODELODORMITORIO PRIMARY KEY(COD)
);

CREATE TABLE MONTADOR
(
	NIF VARCHAR2(10),
	NOMBRE VARCHAR2(30),
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	
	CONSTRAINT PK_MONTADOR
);

CREATE TABLE MONTA
(
	MODELO VARCHAR2(20),
	NIF_M VARCHAR2(10),
	FECHAMONTAJE DATE,
	
	CONSTRAINT PK_MONTA PRIMARY KEY (MODELO,NIF_M,FCHAMONTAJE),
	CONSTRAINT FK1_MONTA FOREIGN KEY (MODELO) REFERENCES MODELO DORMITORIO(COD),
	CONSTRAINT FK2_MONTA FOREIGN KEY (NIF_M) REFERENCES MONTADOR(NIF)
);
CREATE TABLE COMPRA
(
	NIF_C VARCHAR2(10),
	MODELO VARCHAR2(30),
	FECHACOMPRA DATE,
	
	CONSTRAINT PK_COMPRA PRIMARY KEY (NIF_C, MODELO, FECHACOMPRA),
	CONSTRAINT FK1_COMPRA FOREIGN KEY (NIF_C) REFERENCES CLIENTE(NIF),
	CONSTRAINT FK2_COMPRA FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO(COD)
);
