CREATE TABLE MUNICIPIO
(
	ID VARCHAR2(10),
	NOMBRE VARCHAR2 (30) NOT NULL,
	CODPOSTAL VARCHAR2(5),
	PROVINCIA VARCHAR2(20),
	
	CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID)
);

CREATE TABLE VIVIENDA
(
	ID VARCHAR2(10),
	TIPOVIA VARCHAR2(10) DEFAULT 'CALLE',
	NOMBREVIA VARCHAR2(20) NOT NULL,
	NUMERO VARCHAR2(4) NOT NULL,
	IDMUNICIPIO VARCHAR2(10),
	
	CONSTRAINT PK_VIVIENDA PRIMARY KEY(ID),
	CONSTRAINT FK1_VIVIENDA FOREIGN KEY(IDMUNICIPIO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE PERSONA
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHANAC DATE,
	SEXO VARCHAR2(1),
	IDVIVIENDA VARCHAR2(10),
	
	CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
	CONSTRAINT FK1_PERSONA FOREIGN KEY (IDVIVIENDA) REFERENCES VIVIENDA(ID),
	CONSTRAINT CHK_SEXO CHECK (SEXO IN ('M','H'))
);

CREATE TABLE CABEZAFAMILIA
(
	DNI VARCHAR2(10),
	IDVIVIENDA VARCHAR2(10) UNIQUE,
	
	CONSTRAINT PK_CABEZAFAMILIA PRIMARY KEY (DNI),
	CONSTRAINT FK1_CABEZAFAMILIA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
	CONSTRAINT FK2_CABEZAFAMILIA FOREIGN KEY (IDVIVIENDA) REFERENCES VIVIENDA(ID)
);

CREATE TABLE POSEE
(
	DNI VARCHAR2(10),
	IDVIVIENDA VARCHAR2(10),
	
	CONSTRAINT PK_POSEE PRIMARY KEY (DNI),
	CONSTRAINT FK1_POSEE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
	CONSTRAINT FK2_POSEE FOREIGN KEY (IDVIVIENDA) REFERENCES VIVIENDA(ID)
);