CREATE TABLE SUCURSAL
(
	CODSUCURSAL NUMBER(10),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(30),
	LOCALIDAD VARCHAR2(30)
	
);

CREATE TABLE CLIENTE
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	DIRECION VARCHAR2(30),
	LOCALIDAD VARCHAR2(20),
	FECHANAC DATE,
	SEXO VARCHAR2(1)
);

CREATE TABLE CUENTA
(
	CODSUCURSAL NUMBER(10),
	CODCUENTA VARCHAR2(10)
	
);

CREATE TABLE TRANSACCION
(
	CODSUCURSAL NUMBER(10),
	CODCUENTA VARCHAR2(10),
	NUMTRANSACCION NUMBER(20),
	FECHA DATE,
	CANTIDAD NUMBER(20,2),
	TIPO VARCHAR2(20)
	

);

CREATE TABLE CLI_CUENTA
(
	CODSUCURSAL NUMBER(10),
	CODCUENTA VARCHAR2(10),
	DNI VARCHAR2(10)
);

-- Tabla sucursual
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY(CODSUCURSAL);
CREATE SEQUENCE SEC_CODSUCURSAL START WITH 101 INCREMENT BY 1 MAXVALUE 99999999999 MINVALUE 1;
select SEC_CODSUCURSAL.CURRVAL from dual;

--Tabla cliente
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI);

--Tabla cuenta
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY(CODSUCURSAL,CODCUENTA);
ALTER TABLE CUENTA ADD CONSTRAINT FK1_CUENTA FOREIGN KEY(CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);


--Tabla transaccion
ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSACCION PRIMARY KEY(CODSUCURSAL,CODCUENTA);
ALTER TABLE TRANSACCION ADD CONSTRAINT FK1_CODSURSAL FOREIGN KEY(CODSUCURSAL,CODCUENTA) REFERENCES CUENTA(CODSUCURSAL,CODCUENTA);

--Tabla Cli-cuenta
ALTER TABLE CLI_CUENTA ADD CONSTRAINT PK_CLI_CUENTA PRIMARY KEY(CODSUCURSAL,CODCUENTA,DNI);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK1_CLI_CUENTA FOREIGN KEY(CODSUCURSAL,CODCUENTA) REFERENCES CUENTA(CODSUCURSAL,CODCUENTA);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT FK2_CLI_CUENTA FOREIGN KEY(DNI) REFERENCES CLIENTE(DNI);


--Prueba sequencia

INSERT INTO SUCURSAL VALUES (SEC_CODSUCURSAL.NEXTVAL,'Arcachofa','Cantillana','Caceres');
SELECT * FROM SUCURSAL;
