CREATE TABLE DIRECCION
(
	CODDIRECCION VARCHAR2(10),
	VIA VARCHAR2(10),
	NOMBREVIA VARCHAR2(20),
	NUMERO NUMBER(3),
	PISO NUMBER(3),
	PORTAL NUMBER (3),
	CODPOSTAL NUMBER(5),
	
	CONSTRAINT PK_DIRECCION PRIMARY KEY (CODDIRECCION)
);

CREATE TABLE ARTICULO
(
	NUMARTICULO NUMBER(4),
	DESCRIPCION VARCHAR2 (100),
	
	CONSTRAINT PK_ARTICULO PRIMARY KEY (NUMARTICULO)
);

CREATE TABLE FABRICA
(
	NUMFABRICA NUMBER(5),
	TELEFONO NUMBER(10),
	
	CONSTRAINT PK_FABRICA PRIMARY KEY (NUMFABRICA)
);

CREATE TABLE CLIENTE
(
	NUMCLIENTE NUMBER(3),
	SALDO NUMBER(20,2),
	LIMCREDITO NUMBER(20,2),
	DESCUENTO NUMBER(3),
	
	CONSTRAINT PK_CLIENTE PRIMARY KEY (NUMCLIENTE)
);

CREATE TABLE PEDIDO
(
	NUMPEDIDO NUMBER(10),
	FECHA DATE,
	NUMCLIENTE NUMBER(3),
	CODDIRECCION
	
	CONSTRAINT PK_PEDIDO
	CONSTRAINT FK1_PEDIDO
	CONSTRAINT FK2_PEDIDO
);

CREATE TABLE POSEE
(

);

CREATE TABLE INCLUYE();
CREATE TABLE DISTRIBUYE();