CREATE TABLE VEHICULOS
(
	MATRICULA VARCHAR2(7),
	MARCA VARCHAR2(10) NOT NULL,
	MODELO VARCHAR2(10) NOT NULL,
	FECHA_COMPRA DATE ,
	PRECIO_DIA NUMBER(4,2),
	
	CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA),
	CONSTRAINT CHK_PRECIO CHECK (PRECIO_DIA>0)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR2(30),
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(50),
	
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILERES
(
	MATRICULA VARCHAR2(7),
	DNI VARCHAR2(10),
	FECHA_HORA DATE,
	NUM_DIAS NUMBER(2) NOT NULL,
	KILOMETROS NUMBER(4) DEFAULT 0,
	
	CONSTRAINT PK_ALQUILERES PRIMARY KEY(MATRICULA,DNI,FECHA_HORA),
	CONSTRAINT FK1_ALQUILERES FOREIGN KEY(DNI) REFERENCES CLIENTES(DNI),
	CONSTRAINT FK2_ALQUILERES FOREIGN KEY(MATRICULA) REFERENCES VEHICULOS(MATRICULA)
);


--Tabla vehiculos
ALTER TABLE VEHICULOS ADD CONSTRAINT CHK_FECHA_COMPRA CHECK (FECHA_COMPRA> TO_DATE('01/01/2001','DD/MM/YYYY'));
ALTER TABLE VEHICULOS ADD CONSTRAINT CHK_MATRICULA CHECK (REGEXP_LIKE(MATRICULA,'^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE VEHICULOS ADD KM_TOTALES NUMBER(5);

--Tabla clientes
ALTER TABLE CLIENTES ADD CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(DNI,'^[1-9]{8}-[A-Z]$'));
