CREATE TABLE EQUIPOS
(
	CODEQUIPO VARCHAR(4),
	NOMBRE VARCHAR(30) NOT NULL,
	LOCALIDAD VARCHAR(15),
	
	CONSTRAINT PK_EQUIPOS PRIMARY KEY(CODEQUIPO)
);

CREATE TABLE JUGADORES
(
	CODJUGADOR VARCHAR(4),
	NOMBRE VARCHAR(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DEMARCACION VARCHAR(10),
	CODEQUIPO VARCHAR(4),
	
	CONSTRAINT PK_JUGADORES PRIMARY KEY (CODJUGADOR),
	CONSTRAINT FK1_JUGADORES FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPOS(CODEQUIPO)
);

CREATE TABLE PARTIDOS
(
	CODPARTIDO VARCHAR(4),
	CODEQUIPOLOCAL VARCHAR(4),
	CODEQUIPOVISITANTE VARCHAR(4),
	FECHA DATE,
	COMPETICION VARCHAR(4),
	JORNADA VARCHAR(20),
	
	CONSTRAINT PK_PARTIDOS PRIMARY KEY (CODPARTIDO),
	CONSTRAINT FK1_PARTIDOS FOREIGN KEY (CODEQUIPOLOCAL) REFERENCES EQUIPOS(CODEQUIPO),
	CONSTRAINT FK2_PARTIDOS FOREIGN KEY (CODEQUIPOVISITANTE) REFERENCES EQUIPOS(CODEQUIPO)
);

CREATE TABLE INCIDENCIAS
(
	NUMINCIDENCIA VARCHAR(6),
	CODPARTIDO VARCHAR(4),
	CODJUGADOR VARCHAR(4),
	MINUTO INT(2),
	TIPO VARCHAR(20),
	
	CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUMINCIDENCIA),
	CONSTRAINT FK1_INCIDENCIAS FOREIGN KEY (CODPARTIDO) REFERENCES PARTIDOS(CODPARTIDO),
	CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (CODJUGADOR) REFERENCES JUGADORES(CODJUGADOR)
);

#Tabla partidos
ALTER TABLE PARTIDOS ADD CONSTRAINT CHK_FECHA CHECK (MONTH(FECHA) NOT IN (07,08));
ALTER TABLE PARTIDOS ADD CONSTRAINT CHK_COMPETICION CHECK(COMPETICION IN('Copa','Liga'));

#Alternativa
#ALTER TABLE PARTIDOS ADD CONSTRAINT CHK_FECHA CHECK (MONTH(FECHA) NOT IN (07, 08));
#Tabla Incidencias
ALTER TABLE INCIDENCIAS ADD CONSTRAINT CHK_MINUTO CHECK(MINUTO BETWEEN 1 AND 100);

#Tabla jugadores
ALTER TABLE JUGADORES ADD CONSTRAINT CHK_NOMBRE CHECK(NOMBRE = INITCAP(NOMBRE));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK_DEMARCACION CHECK(DEMARCACION IN('Portero','Defensa','Medio','Delantero'));

#Tabla equipos
ALTER TABLE EQUIPOS ADD CONSTRAINT CHK_CODEQUIPO CHECK (REGEXP_LIKE(CODEQUIPO,'^[0-9].*'));
ALTER TABLE EQUIPOS ADD GOLESMARCADOS INT(3);

#Tabla incidencias
ALTER TABLE INCIDENCIAS MODIFY TIPO NOT NULL;



