CREATE TABLE TEMA
(
	COD_TEMA NUMBER(5),
	DENOMINACION VARCHAR2(30),
	COD_TEMA_PADRE NUMBER(5),
	
	CONSTRAINT PK_TEMA PRIMARY KEY(COD_TEMA),
	CONSTRAINT FK1_TEMA FOREIGN KEY(COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA) 
);

CREATE TABLE LIBRO
(
	COD_LIBRO VARCHAR2(5),
	F_CREACION DATE,
	COD_TEMA NUMBER(5),
	AUTOR_PRINCIPAL VARCHAR2(20),
	
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
	CONSTRAINT FK1_LIBRO FOREIGN KEY(COD_TEMA) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE AUTOR
(
	COD_AUTOR VARCHAR2(5),
	NOMBRE VARCHAR2(20),
	F_NACIMIENTO DATE,
	LIBRO_PRINCIPAL VARCHAR2(20),
	
	CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR)
);


CREATE TABLE LIBRO_AUTOR
(
	COD_LIBRO VARCHAR2(5),
	COD_AUTOR VARCHAR2(5),
	ORDEN NUMBER(1),
	
	CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO,COD_AUTOR),
	CONSTRAINT FK1_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE EDITORIAL
(
	COD_EDITORIAL VARCHAR2(5),
	DENOMINACION VARCHAR2(20),
	
	CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);


CREATE TABLE PUBLICACIONES
(
	COD_EDITORIAL VARCHAR2(5),
	COD_LIBRO VARCHAR2(5),
	PRECIO NUMBER (5,2) NOT NULL,
	F_PUBLICACION DATE DEFAULT SYSDATE,
	
	CONSTRAINT PK_PUBLICACIONES PRIMARY KEY(COD_EDITORIAL,COD_LIBRO,F_PUBLICACION),
	CONSTRAINT FK1_PUBLICACIONES FOREIGN KEY(COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY(COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL)
);



--Tabla autor
ALTER TABLE AUTOR ADD CONSTRAINT FK1_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO);

--Tabla libro
ALTER TABLE LIBRO ADD CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR);

--Tabla libro_autor
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT CHK_ORDEN CHECK (ORDEN IN('1','2','3','4','5'));

--Tabla tema
ALTER TABLE TEMA ADD CONSTRAINT CHK1_ORDEN CHECK (COD_TEMA_PADRE<COD_TEMA);

--Tabla publicaiones
ALTER TABLE PUBLICACIONES ADD CONSTRAINT CHK1_PRECIO CHECK (PRECIO>0);




--1. Nos hemos dado cuenta que una misma editorial puede publicar varias veces el mismo libro.
--Razona si se podría hacer, y en caso contrario indica las órdenes a seguir.

-- No sería posible ya que en la tabla libro existe cod_libro es primary key, lo cual el libro que quieran introducir si ya existe en la bbdd al volver a meter el mismo cod_lbro violaria la pk de la misma tabla.

--2. Borra todas las tablas creadas. 

DROP TABLE TEMA ON DELETE CASCADE;
DROP TABLE LIBRO ON DELETE CASCADE;
DROP TABLE AUTOR ON DELETE CASCADE;
DROP TABLE LIBRO_AUTOR ON DELETE CASCADE;
DROP TABLE EDITORIAL ON DELETE CASCADE;
DROP TABLE PUBLICACIONES ON DELETE CASCADE;